// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enlwcfcwszlqkdwtxoxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVubHdjZmN3c3pscWtkd3R4b3h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMjE1OTEsImV4cCI6MjA2NzU5NzU5MX0.hEqMUvf5hI48aVsvLPAzapQjhbr6MV2KpIyfdSc7pT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});